version: 2

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      github-actions:
        patterns:
          - "*"
  - package-ecosystem: "cargo"
    directories:
      - "/"
      - "/crates/*"
    schedule:
      interval: "weekly"
    groups:
      cargo:
        patterns:
          - "*"
  - package-ecosystem: "npm"
    directory: "/editors/code"
    schedule:
      interval: "weekly"
    ignore:
      # This must match the oldest supported VS Code API in `engines.vscode`.
      - dependency-name: "@types/vscode"
    groups:
      npm:
        patterns:
          - "*"
