//! Oracle harness for incremental reparse (Tenet 4).
//!
//! For every snippet and ~200 seeded edits, any `Some(Reparsed)` from
//! [`fatou::parser::reparse`] must be byte-identical to a full parse of the
//! edited text: same tree fingerprint (kind@range + token text of every
//! descendant, shared with the in-crate Tenet-4 `debug_assert`) and the same
//! diagnostics vector, order included. A `None` is always correct — the
//! caller falls back to a full parse — so the harness is trivially green
//! while the stage-0 stub falls back on everything, and becomes the safety
//! net the token and top-level tiers are developed against.
//!
//! Edits are generated by a tiny seeded LCG (reproducible; the seed is in
//! every assert message) with an insert alphabet biased toward lexical
//! hazards: string delimiters, interpolation, adjoint/char quotes, comments,
//! newlines, `end`/`function`, digits and `e10` juxtaposition, `α`.

use std::fs;
use std::path::{Path, PathBuf};

use fatou::parser::{Edit, ReparseTier, Reparsed, fingerprint, parse, reparse};
use fatou::syntax::SyntaxNode;

const EDITS_PER_SNIPPET: usize = 200;

/// Insert alphabet, hazard-biased: most entries can change how neighboring
/// text lexes (string modes, comments, juxtaposition, statement boundaries).
const INSERTS: &[&str] = &[
    "\"", "\"\"\"", "$", "'", "#", "=#", "\n", ";", "end", "function", "1", "0", "e10", "+", "α",
    " ", "x",
];

/// Minimal deterministic PRNG (MMIX LCG); enough to scatter edits without
/// pulling in a rand dependency.
struct Lcg(u64);

impl Lcg {
    fn next(&mut self) -> u64 {
        self.0 = self
            .0
            .wrapping_mul(6364136223846793005)
            .wrapping_add(1442695040888963407);
        self.0 >> 33
    }

    fn pick(&mut self, n: usize) -> usize {
        (self.next() % n as u64) as usize
    }
}

/// Generate [`EDITS_PER_SNIPPET`] seeded edits against `src`: inserts from
/// the hazard alphabet (majority), plus single-char deletions and
/// replacements. All offsets are char boundaries, so slicing never panics.
fn seeded_edits(src: &str, seed: u64) -> Vec<Edit> {
    let boundaries: Vec<usize> = (0..=src.len())
        .filter(|&i| src.is_char_boundary(i))
        .collect();
    let mut rng = Lcg(seed ^ 0x9E37_79B9_7F4A_7C15);
    let mut edits = Vec::with_capacity(EDITS_PER_SNIPPET);
    for _ in 0..EDITS_PER_SNIPPET {
        let start = boundaries[rng.pick(boundaries.len())];
        let next = (start + 1..=src.len()).find(|&i| src.is_char_boundary(i));
        let action = rng.pick(10);
        let edit = match (action, next) {
            // ~20% deletions, ~10% replacements, rest insertions; degrade to
            // insertion at EOF where there is no char to delete.
            (0 | 1, Some(end)) => Edit {
                range: start..end,
                insert: String::new(),
            },
            (2, Some(end)) => Edit {
                range: start..end,
                insert: INSERTS[rng.pick(INSERTS.len())].to_string(),
            },
            _ => Edit {
                range: start..start,
                insert: INSERTS[rng.pick(INSERTS.len())].to_string(),
            },
        };
        edits.push(edit);
    }
    edits
}

/// The oracle: whenever `reparse` claims success, its tree and diagnostics
/// must match a full parse of the edited text exactly.
fn check_snippet(src: &str, seed: u64) {
    let old = parse(src);
    let old_green = old.cst.green().into_owned();
    for edit in seeded_edits(src, seed) {
        let new_text = edit.apply(src);
        let Some(rep) = reparse(src, &old_green, &old.diagnostics, &edit, &new_text) else {
            continue; // fallback to full parse is always correct
        };
        let full = parse(&new_text);
        assert_eq!(
            fingerprint(&SyntaxNode::new_root(rep.green.clone())),
            fingerprint(&full.cst),
            "reparse ({:?}) tree mismatch, seed {seed}, edit {edit:?} on:\n{src}",
            rep.tier,
        );
        assert_eq!(
            rep.diagnostics, full.diagnostics,
            "reparse ({:?}) diagnostics mismatch, seed {seed}, edit {edit:?} on:\n{src}",
            rep.tier,
        );
    }
}

/// Hand-written hazard snippets: each encodes a known reparse trap
/// (docstring folding, string modes, adjoint vs char, juxtaposition,
/// trailing-operator continuation, toplevel-contextual forms, error
/// recovery on junk and unterminated literals).
const HAZARD_SNIPPETS: &[&str] = &[
    // Docstring + declaration: fold_docstrings is cross-statement.
    "\"\"\"\ndoc\n\"\"\"\nfunction f(x)\n    x\nend\n",
    // Triple, raw, and prefixed strings, with interpolation.
    "s = \"\"\"a $(x + 1) b\"\"\"\n",
    "p = raw\"a\\\\b$x\"\n",
    "re = r\"^a$\"\n",
    "bs = b\"bytes\"\n",
    // `end` as an index marker inside brackets.
    "a[end-1]\n",
    // Adjoint vs char literal.
    "y = x'\n",
    "c = 'x'\n",
    // Juxtaposition: editing `x` can fuse into a float (`2e10`).
    "y = 2x\n",
    // Trailing-operator continuation across a newline.
    "x = 1 +\n    2\ny = 3\n",
    // Trailing junk after a complete expression.
    "x y\n",
    // Toplevel semicolon sequence.
    "a; b\n",
    // Stray closers.
    "f(x))\n",
    "end\n",
    // Unterminated literals.
    "x = \"abc",
    "c = 'a",
    "#= open\n",
    // Toplevel-contextual and flag-pass forms.
    "public a, b\n",
    "const x = 1\n",
    "const x\n",
    // Degenerate inputs.
    "",
    "\n",
];

/// Run one edit through `reparse` against a fresh parse of `src`. The
/// Tenet-4 `debug_assert` inside `reparse` already cross-checks any success
/// against a full parse, so the targeted tests below only assert *whether*
/// the token tier fired, not correctness.
fn try_reparse(src: &str, range: std::ops::Range<usize>, insert: &str) -> Option<Reparsed> {
    let old = parse(src);
    let green = old.cst.green().into_owned();
    let edit = Edit {
        range,
        insert: insert.to_string(),
    };
    let new_text = edit.apply(src);
    reparse(src, &green, &old.diagnostics, &edit, &new_text)
}

#[track_caller]
fn assert_token_tier(src: &str, range: std::ops::Range<usize>, insert: &str) {
    let rep = try_reparse(src, range.clone(), insert)
        .unwrap_or_else(|| panic!("token tier should fire for {range:?} {insert:?} on {src:?}"));
    assert_eq!(rep.tier, ReparseTier::Token);
}

#[track_caller]
fn assert_falls_back(src: &str, range: std::ops::Range<usize>, insert: &str) {
    assert!(
        try_reparse(src, range.clone(), insert).is_none(),
        "expected fallback for {range:?} {insert:?} on {src:?}"
    );
}

#[track_caller]
fn assert_toplevel_tier(src: &str, range: std::ops::Range<usize>, insert: &str) {
    let rep = try_reparse(src, range.clone(), insert).unwrap_or_else(|| {
        panic!("top-level tier should fire for {range:?} {insert:?} on {src:?}")
    });
    assert_eq!(rep.tier, ReparseTier::TopLevel);
}

#[track_caller]
fn assert_not_token_tier(src: &str, range: std::ops::Range<usize>, insert: &str) {
    if let Some(rep) = try_reparse(src, range.clone(), insert) {
        assert_ne!(
            rep.tier,
            ReparseTier::Token,
            "token tier must not splice {range:?} {insert:?} on {src:?}"
        );
    }
}

/// Stage-2 positive cases: the token tier must handle the classic in-leaf
/// edits, including the boundary insertion at the end of an identifier (the
/// most common keystroke) and diagnostic shifting past the edit.
#[test]
fn token_tier_fires() {
    // Mid-identifier replacement and boundary append (`Between` candidate).
    assert_token_tier("foo = 1\n", 1..2, "x");
    assert_token_tier("foo = 1\n", 3..3, "d");
    // Line-comment and block-comment interiors.
    assert_token_tier("x = 1 # note\n", 9..9, "o");
    assert_token_tier("#= a =#\n", 4..4, "b");
    // Widening a whitespace run.
    assert_token_tier("x  = 1\n", 2..2, " ");
    // Multi-byte identifier edit.
    assert_token_tier("αβ = 1\n", 2..4, "γ");
    // A diagnostic after the leaf (stray closer) shifts by the delta; the
    // in-crate Tenet-4 assert validates the shifted positions.
    assert_token_tier("foo = 1\ng(x))\n", 1..2, "oo");
}

/// Stage-2 negative cases: each known hazard must escape the token tier.
/// Since the top-level statement tier landed, most are legally handled there
/// instead of falling back to a full parse (the Tenet-4 assert inside
/// `reparse` validates any such splice); the token tier's guards are what
/// these cases pin.
#[test]
fn token_tier_falls_back() {
    // Identifier becomes a keyword or a contextual identifier.
    assert_not_token_tier("fo = 1\n", 2..2, "r");
    assert_not_token_tier("publik = 1\n", 5..6, "c");
    // Editing a contextual identifier that currently shapes the tree.
    assert_not_token_tier("public a, b\n", 0..1, "q");
    // Juxtaposition fuses across the backward boundary (`2e10` is one Float).
    assert_not_token_tier("y = 2x\n", 5..6, "e10");
    // A newline changes statement structure.
    assert_not_token_tier("x  = 1\n", 2..2, "\n");
    // String content lexing depends on the enclosing delimiter mode.
    assert_not_token_tier("s = \"abc\"\n", 6..7, "x");
    // Numeric leaves are ineligible.
    assert_not_token_tier("x = 12\n", 5..5, "3");
    // `#=` nests, leaving the trailing block comment unterminated at EOF;
    // the sentinel forward probe catches it.
    assert_not_token_tier("#= a =#", 3..3, "#=");
    // A diagnostic touching the edited leaf (trailing junk on `y`).
    assert_not_token_tier("x y\n", 2..3, "z");
}

/// Stage-3 positive cases: the top-level statement tier must handle the
/// classic region edits. Each uses an edit the token tier rejects (multi-token
/// inserts, digits, string content, newlines), and the in-crate Tenet-4
/// assert validates every splice against a full parse.
#[test]
fn toplevel_tier_fires() {
    // Edit inside a function body with statement neighbors on both sides.
    assert_toplevel_tier("a = 1\nfunction f(x)\n    x\nend\nb = 2\n", 25..25, " + 1");
    // Docstring-content edit: the region is the whole `DOC` child.
    assert_toplevel_tier(
        "\"\"\"\ndoc\n\"\"\"\nfunction f(x)\n    x\nend\nx = 1\n",
        5..5,
        "s",
    );
    // Flag-stream splice: editing a neighbor keeps the `const x` diagnostic
    // before the region and shifts the one after it.
    assert_toplevel_tier("const x\ny = 1\nconst z\n", 12..13, "22");
    // Completing `const x` into an assignment drops the zero-width
    // `ConstNotAssignment` anchored exactly at the region start.
    assert_toplevel_tier("const x\ny = 1\n", 7..7, " = 2");
    // New statement at BOF (the insert spans a newline, so the token tier is
    // out from the start).
    assert_toplevel_tier("x = 1\ny = 2\n", 0..0, "a = 0\n");
    // New statement at EOF.
    assert_toplevel_tier("x = 1\ny = 2\n", 12..12, "z = 3\n");
    // Typing a statement on a blank line between two statements.
    assert_toplevel_tier("a = 1\n\nb = 2\n", 6..6, "c = 3");
    // A `TOPLEVEL_SEMICOLON` line as the untouched previous sibling.
    assert_toplevel_tier("a; b\nc = 1\n", 9..10, "2");
}

/// Stage-3 negative cases: cross-boundary hazards must fall back.
#[test]
fn toplevel_tier_falls_back() {
    // Statement becomes a docstring: deleting the blank line lets
    // `fold_docstrings` fold the string with the following statement, which
    // the backward boundary parse sees as a `DOC` node straddling the seam.
    assert_falls_back("\"note\"\n\nx = 1\n", 7..8, "");
    // Forward absorption: an unterminated block swallows the next statement.
    assert_falls_back("x = 1\ny = 2\n", 0..0, "function g()\n");
    // Trailing-operator continuation across the region's forward boundary.
    assert_falls_back("x = 1\ny = 2\n", 5..5, " +");
    // Same-line trailing junk: no decoupling newline before the region.
    assert_falls_back("x y\n", 2..3, "z");
    // The region covers every `ROOT` child (single statement, no trailing
    // newline): the fragment reparse would be the full parse.
    assert_falls_back("x = 1", 4..5, "2");
}

/// Character-by-character typing of a function into the blank line of an
/// existing file. Only the meaningful steps are pinned; the in-between steps
/// are a legal mix of token-tier hits, fallbacks, and broken-to-broken
/// top-level splices, each oracle-checked by the Tenet-4 `debug_assert`
/// inside `reparse`.
#[test]
fn toplevel_tier_char_by_char_typing() {
    let typed = "function g(x)\n    x\nend\n";
    let mut src = "a = 1\n\nb = 2\n".to_string();
    let insert_at = 6;
    for (i, ch) in typed.char_indices() {
        let pos = insert_at + i;
        let rep = try_reparse(&src, pos..pos, &ch.to_string());
        match i {
            // The first typed char is a statement on the blank line.
            0 => assert_eq!(
                rep.map(|r| r.tier),
                Some(ReparseTier::TopLevel),
                "step {i}: expected top-level splice"
            ),
            // The `n` completing the `function` keyword: the token tier sees
            // a kind flip and the top-level fragment would swallow `b = 2`.
            7 => assert!(rep.is_none(), "step {i}: expected fallback"),
            // The `d` completing `end` closes the block mid-line: the broken
            // `FUNCTION` node had swallowed `b = 2`, so the region is that
            // whole node and the splice replaces one child with several.
            22 => assert_eq!(
                rep.map(|r| r.tier),
                Some(ReparseTier::TopLevel),
                "step {i}: expected top-level splice"
            ),
            // The final newline: the token tier bans newlines.
            23 => assert_eq!(
                rep.map(|r| r.tier),
                Some(ReparseTier::TopLevel),
                "step {i}: expected top-level splice"
            ),
            _ => {}
        }
        src.insert(pos, ch);
    }
}

#[test]
fn hazard_snippets() {
    for (i, src) in HAZARD_SNIPPETS.iter().enumerate() {
        check_snippet(src, i as u64);
    }
}

/// Broad sweep over the differential-oracle corpus inputs
/// (`tests/fixtures/oracle/<slug>/input.jl`).
#[test]
fn oracle_corpus() {
    let dir = Path::new(env!("CARGO_MANIFEST_DIR")).join("tests/fixtures/oracle");
    let mut inputs: Vec<PathBuf> = fs::read_dir(&dir)
        .expect("read oracle corpus dir")
        .filter_map(|entry| {
            let path = entry.expect("read corpus entry").path();
            let input = path.join("input.jl");
            input.is_file().then_some(input)
        })
        .collect();
    inputs.sort();
    assert!(!inputs.is_empty(), "oracle corpus is empty at {dir:?}");
    for (i, path) in inputs.iter().enumerate() {
        let src = fs::read_to_string(path).expect("read input.jl");
        check_snippet(&src, 1000 + i as u64);
    }
}
