//! Oracle harness for incremental reparse (Tenet 4).
//!
//! For every snippet and ~200 seeded edits, any `Some(Reparsed)` from
//! [`fatou::parser::reparse`] must be byte-identical to a full parse of the
//! edited text: same tree fingerprint (kind@range + token text of every
//! descendant, shared with the in-crate Tenet-4 `debug_assert`) and the same
//! diagnostics vector, order included. A `None` is always correct — the
//! caller falls back to a full parse — so the harness is trivially green
//! while the stage-0 stub falls back on everything, and becomes the safety
//! net the token and top-level tiers are developed against.
//!
//! Edits are generated by a tiny seeded LCG (reproducible; the seed is in
//! every assert message) with an insert alphabet biased toward lexical
//! hazards: string delimiters, interpolation, adjoint/char quotes, comments,
//! newlines, `end`/`function`, digits and `e10` juxtaposition, `α`.

use std::fs;
use std::path::{Path, PathBuf};

use fatou::parser::{Edit, fingerprint, parse, reparse};
use fatou::syntax::SyntaxNode;

const EDITS_PER_SNIPPET: usize = 200;

/// Insert alphabet, hazard-biased: most entries can change how neighboring
/// text lexes (string modes, comments, juxtaposition, statement boundaries).
const INSERTS: &[&str] = &[
    "\"", "\"\"\"", "$", "'", "#", "=#", "\n", ";", "end", "function", "1", "0", "e10", "+", "α",
    " ", "x",
];

/// Minimal deterministic PRNG (MMIX LCG); enough to scatter edits without
/// pulling in a rand dependency.
struct Lcg(u64);

impl Lcg {
    fn next(&mut self) -> u64 {
        self.0 = self
            .0
            .wrapping_mul(6364136223846793005)
            .wrapping_add(1442695040888963407);
        self.0 >> 33
    }

    fn pick(&mut self, n: usize) -> usize {
        (self.next() % n as u64) as usize
    }
}

/// Generate [`EDITS_PER_SNIPPET`] seeded edits against `src`: inserts from
/// the hazard alphabet (majority), plus single-char deletions and
/// replacements. All offsets are char boundaries, so slicing never panics.
fn seeded_edits(src: &str, seed: u64) -> Vec<Edit> {
    let boundaries: Vec<usize> = (0..=src.len())
        .filter(|&i| src.is_char_boundary(i))
        .collect();
    let mut rng = Lcg(seed ^ 0x9E37_79B9_7F4A_7C15);
    let mut edits = Vec::with_capacity(EDITS_PER_SNIPPET);
    for _ in 0..EDITS_PER_SNIPPET {
        let start = boundaries[rng.pick(boundaries.len())];
        let next = (start + 1..=src.len()).find(|&i| src.is_char_boundary(i));
        let action = rng.pick(10);
        let edit = match (action, next) {
            // ~20% deletions, ~10% replacements, rest insertions; degrade to
            // insertion at EOF where there is no char to delete.
            (0 | 1, Some(end)) => Edit {
                range: start..end,
                insert: String::new(),
            },
            (2, Some(end)) => Edit {
                range: start..end,
                insert: INSERTS[rng.pick(INSERTS.len())].to_string(),
            },
            _ => Edit {
                range: start..start,
                insert: INSERTS[rng.pick(INSERTS.len())].to_string(),
            },
        };
        edits.push(edit);
    }
    edits
}

/// The oracle: whenever `reparse` claims success, its tree and diagnostics
/// must match a full parse of the edited text exactly.
fn check_snippet(src: &str, seed: u64) {
    let old = parse(src);
    let old_green = old.cst.green().into_owned();
    for edit in seeded_edits(src, seed) {
        let new_text = edit.apply(src);
        let Some(rep) = reparse(src, &old_green, &old.diagnostics, &edit, &new_text) else {
            continue; // fallback to full parse is always correct
        };
        let full = parse(&new_text);
        assert_eq!(
            fingerprint(&SyntaxNode::new_root(rep.green.clone())),
            fingerprint(&full.cst),
            "reparse ({:?}) tree mismatch, seed {seed}, edit {edit:?} on:\n{src}",
            rep.tier,
        );
        assert_eq!(
            rep.diagnostics, full.diagnostics,
            "reparse ({:?}) diagnostics mismatch, seed {seed}, edit {edit:?} on:\n{src}",
            rep.tier,
        );
    }
}

/// Hand-written hazard snippets: each encodes a known reparse trap
/// (docstring folding, string modes, adjoint vs char, juxtaposition,
/// trailing-operator continuation, toplevel-contextual forms, error
/// recovery on junk and unterminated literals).
const HAZARD_SNIPPETS: &[&str] = &[
    // Docstring + declaration: fold_docstrings is cross-statement.
    "\"\"\"\ndoc\n\"\"\"\nfunction f(x)\n    x\nend\n",
    // Triple, raw, and prefixed strings, with interpolation.
    "s = \"\"\"a $(x + 1) b\"\"\"\n",
    "p = raw\"a\\\\b$x\"\n",
    "re = r\"^a$\"\n",
    "bs = b\"bytes\"\n",
    // `end` as an index marker inside brackets.
    "a[end-1]\n",
    // Adjoint vs char literal.
    "y = x'\n",
    "c = 'x'\n",
    // Juxtaposition: editing `x` can fuse into a float (`2e10`).
    "y = 2x\n",
    // Trailing-operator continuation across a newline.
    "x = 1 +\n    2\ny = 3\n",
    // Trailing junk after a complete expression.
    "x y\n",
    // Toplevel semicolon sequence.
    "a; b\n",
    // Stray closers.
    "f(x))\n",
    "end\n",
    // Unterminated literals.
    "x = \"abc",
    "c = 'a",
    "#= open\n",
    // Toplevel-contextual and flag-pass forms.
    "public a, b\n",
    "const x = 1\n",
    "const x\n",
    // Degenerate inputs.
    "",
    "\n",
];

#[test]
fn hazard_snippets() {
    for (i, src) in HAZARD_SNIPPETS.iter().enumerate() {
        check_snippet(src, i as u64);
    }
}

/// Broad sweep over the differential-oracle corpus inputs
/// (`tests/fixtures/oracle/<slug>/input.jl`).
#[test]
fn oracle_corpus() {
    let dir = Path::new(env!("CARGO_MANIFEST_DIR")).join("tests/fixtures/oracle");
    let mut inputs: Vec<PathBuf> = fs::read_dir(&dir)
        .expect("read oracle corpus dir")
        .filter_map(|entry| {
            let path = entry.expect("read corpus entry").path();
            let input = path.join("input.jl");
            input.is_file().then_some(input)
        })
        .collect();
    inputs.sort();
    assert!(!inputs.is_empty(), "oracle corpus is empty at {dir:?}");
    for (i, path) in inputs.iter().enumerate() {
        let src = fs::read_to_string(path).expect("read input.jl");
        check_snippet(&src, 1000 + i as u64);
    }
}
