[package]
name = "fatou-formatter"
version = "0.2.1"
edition.workspace = true
readme = "README.md"
description = "Deterministic, rule-based formatter for the Julia language"
license.workspace = true
repository.workspace = true
homepage = "https://fatou.dev"
documentation = "https://docs.rs/fatou-formatter"
authors.workspace = true
include = ["/src/**/*", "/README.md", "/CHANGELOG.md"]
keywords = ["julia", "formatter"]
categories = ["development-tools", "text-processing"]

[dependencies]
fatou-parser = { path = "../fatou-parser", version = "0.1.1" }
rowan = "0.17.0"
schemars = { version = "1.2.1", optional = true }
serde = { version = "1.0.228", features = ["derive"], optional = true }

[features]
default = []
serde = ["dep:serde"]
schema = ["serde", "dep:schemars"]

[package.metadata.docs.rs]
all-features = true
