//! Correctness rules: findings that point at a probable bug or dead code.

mod break_outside_loop;
mod call_arity;
mod const_decl;
mod const_local;
mod duplicate_argument;
mod duplicate_include;
mod duplicate_keyword_argument;
mod duplicate_method;
mod global_const_in_function;
mod include_cycle;
mod julia_version_compat;
mod kwarg_default_mismatch;
mod local_const;
mod missing_include_file;
mod noteq_definition;
mod redefined_constant;
mod type_piracy;
mod undefined_name;
mod unreachable_code;
mod unresolved_import;
mod unused_argument;
mod unused_binding;
mod unused_import;
mod unused_type_parameter;

pub use break_outside_loop::BreakOutsideLoop;
pub use call_arity::CallArity;
pub use const_local::ConstLocal;
pub use duplicate_argument::DuplicateArgument;
pub use duplicate_include::DuplicateInclude;
pub use duplicate_keyword_argument::DuplicateKeywordArgument;
pub use duplicate_method::DuplicateMethod;
pub use global_const_in_function::GlobalConstInFunction;
pub use include_cycle::IncludeCycle;
pub use julia_version_compat::JuliaVersionCompat;
pub use kwarg_default_mismatch::KwargDefaultMismatch;
pub use local_const::LocalConst;
pub use missing_include_file::MissingIncludeFile;
pub use noteq_definition::NotEqDefinition;
pub use redefined_constant::RedefinedConstant;
pub use type_piracy::TypePiracy;
pub use undefined_name::UndefinedName;
pub use unreachable_code::UnreachableCode;
pub use unresolved_import::UnresolvedImport;
pub use unused_argument::UnusedArgument;
pub use unused_binding::UnusedBinding;
pub use unused_import::UnusedImport;
pub use unused_type_parameter::UnusedTypeParameter;
